from pathlib import Path

def patch(rel,repls):
 p=Path(rel);s=p.read_text()
 for old,new in repls:
  if old not in s:raise RuntimeError(f'{rel}: missing anchor {old[:100]!r}')
  if s.count(old)!=1:raise RuntimeError(f'{rel}: nonunique anchor {old[:100]!r} count={s.count(old)}')
  s=s.replace(old,new)
 p.write_text(s)

patch('multi-bagger-dashboard/evidence_gate.py',[
 ("from pathlib import Path\n", "from pathlib import Path\nfrom critical_data_policy import apply as apply_score_policy\n"),
 ("    a['completed_passes']=sum(p.get('status')=='complete' for p in stock.get('passes',{}).values())\n    return stock\n", "    a['completed_passes']=sum(p.get('status')=='complete' for p in stock.get('passes',{}).values())\n    return apply_score_policy(stock)\n"),
 ("      'critical_hold':sum(any(w.get('severity')=='critical' for w in s.get('metadata',{}).get('audit',{}).get('warnings',[])) for s in rows),\n      'full_six_pass_complete'", "      'critical_hold':sum(any(w.get('severity')=='critical' for w in s.get('metadata',{}).get('audit',{}).get('warnings',[])) for s in rows),\n      'scoreable':sum(s.get('metadata',{}).get('score_eligibility',{}).get('scoreable') is True for s in rows),\n      'critical_data_unscored':sum(s.get('metadata',{}).get('score_eligibility',{}).get('status')=='missing_critical_data' for s in rows),\n      'full_six_pass_complete'"),
 ("    if a.get('input_audited_mb_score') is not None:\n", "    q=m.get('score_eligibility',{})\n    if q.get('status')=='missing_critical_data':\n        if m['research'].get('research_mb_score') is not None or m['research'].get('research_ev_score') is not None:\n            raise ValueError('Critical-data stock must have current headline investment scores withheld')\n    if a.get('input_audited_mb_score') is not None:\n")])

patch('multi-bagger-dashboard/watchlist_runtime.py',[
 ("from evidence_gate import evidence_status,audit_summary\n", "from evidence_gate import evidence_status,audit_summary\nfrom critical_data_policy import apply as apply_score_policy, rank_key, headline_mb\n"),
 ("            s=src.get(rec['ticker'],empty_stock(rec['ticker']));m=s.setdefault('metadata',{})\n", "            s=apply_score_policy(src.get(rec['ticker'],empty_stock(rec['ticker'])));m=s.setdefault('metadata',{})\n"),
 ("        rows.sort(key=lambda s:(-(s['metadata'].get('research',{}).get('research_mb_score') if finite(s['metadata'].get('research',{}).get('research_mb_score')) else -1),s['ticker']))\n        for i,s in enumerate(rows,1):s['metadata']['tier_rank']=i;s['rank']=len(out)+1;out.append(s)\n", "        rows.sort(key=rank_key)\n        score_rank=0\n        for s in rows:\n            if finite(headline_mb(s)):score_rank+=1;s['metadata']['tier_rank']=score_rank\n            else:s['metadata']['tier_rank']=None\n            s['rank']=len(out)+1;out.append(s)\n"),
 ("       'ranking_basis':'Within each tier at its own stated market-data date. Cross-list comparisons occur only in the common-date weekly review.'})\n", "       'ranking_basis':'Within each tier, only scoreable stocks receive an MB rank. Missing critical score data is unscored. Cross-list comparisons occur only in the common-date weekly review.'})\n"),
 ("        cr=c['metadata'].get('research',{});cv=cr.get('research_mb_score')\n        valid_actions=[a for a in actions if finite(a['metadata'].get('research',{}).get('research_mb_score'))]\n", "        cr=c['metadata'].get('research',{});cv=headline_mb(c)\n        valid_actions=[a for a in actions if a['metadata'].get('score_eligibility',{}).get('scoreable') and finite(headline_mb(a))]\n"),
 ("        blockers=[]\n        if c['metadata'].get('research_review_required')", "        blockers=[]\n        if not c['metadata'].get('score_eligibility',{}).get('scoreable'):blockers.append('Missing critical score data — unscored')\n        if c['metadata'].get('research_review_required')"),
 ("            evidence_status(s,m.get('review_queue',[]))\n            if m.get('research_review_required'):s['action']='RESEARCH HOLD — new or unresolved evidence'\n", "            evidence_status(s,m.get('review_queue',[]))\n            if not m.get('score_eligibility',{}).get('scoreable'):s['action']='MISSING CRITICAL DATA — unscored; resolve required evidence before ranking'\n            elif m.get('research_review_required'):s['action']='RESEARCH HOLD — new or unresolved evidence'\n")])

patch('multi-bagger-dashboard/index.html',[
 ("const rs=s=>s.metadata?.research||{};\nconst currentPrice", "const rs=s=>s.metadata?.research||{};\nconst scoreEligibility=s=>s.metadata?.score_eligibility||{};\nconst currentPrice"),
 ("const mb=s=>research()?rs(s).research_mb_score:s.multi_bagger_score;\n", "const mb=s=>research()?(scoreEligibility(s).status==='missing_critical_data'?null:rs(s).research_mb_score):s.multi_bagger_score;\n"),
 ("function badge(v){return v==null?'<span title=\"Not available; not zero\">—</span>':`<span class=\"score ${v>=70?'hi':v>=50?'mid':'lo'}\">${num(v)}</span>`}\n", "function badge(v){return v==null?'<span title=\"Not available; not zero\">—</span>':`<span class=\"score ${v>=70?'hi':v>=50?'mid':'lo'}\">${num(v)}</span>`}\nfunction mbBadge(s){let q=scoreEligibility(s);return q.status==='missing_critical_data'?'<span class=\"audit-badge audit-critical\">Missing Critical Data — unscored</span>':badge(mb(s))}\n"),
 ("function tierRank(s){return s.metadata?.tier_rank??s.rank}", "function tierRank(s){return scoreEligibility(s).status==='missing_critical_data'?'—':(s.metadata?.tier_rank??s.rank)}"),
 (" · research scores, not buy signals. Each price shows its actual market date; weekly comparison uses a common cutoff.", " · scoreable names ranked; critical-data names unscored. These are research screens, not buy signals. Each price shows its actual market date; weekly comparison uses a common cutoff."),
 ("<td>${badge(mb(s))}${auditBadge(s)}${change(s,'research_mb_score')}", "<td>${mbBadge(s)}${auditBadge(s)}${change(s,'research_mb_score')}"),
 ("<span>MB ${badge(mb(s))}</span>", "<span>MB ${mbBadge(s)}</span>"),
 (" let current=state.snapshot.stocks,reviewed=current.filter(s=>au(s)?.input_audited_mb_score!=null).length,has=current.filter(s=>au(s)).length;\n $('auditBanner').innerHTML=has?`<strong>${has}/${current.length} source-backed scorecards · ${reviewed} passed the stated input-audit checks · ${current.length-reviewed} provisional.</strong><p>MB is an eight-factor investment screen, not an average of six pass scores. Each available factor links to its saved inputs and evidence; unreviewed entries stay unscored. Missing inputs, source limitations, and unresolved transactions are flagged below and in each stock’s detail. Full six-pass research is not yet certified for any stock in this run. “Inputs audited” covers the stated calculation checks only; it does not validate future returns.</p>`", " let current=state.snapshot.stocks,reviewed=current.filter(s=>au(s)?.input_audited_mb_score!=null).length,has=current.filter(s=>au(s)).length,critical=current.filter(s=>scoreEligibility(s).status==='missing_critical_data').length,scoreable=current.length-critical;\n $('auditBanner').innerHTML=has?`<strong>${has}/${current.length} source-backed scorecards · ${scoreable} scoreable · ${critical} Missing Critical Data and unscored · ${reviewed} passed the narrower input-audit checklist.</strong><p>Required MB factor or material score-driving capital/perimeter data must be present for a headline MB/E&V score. Critical gaps are not reweighted and receive no rank. Noncritical historical/source warnings stay visible. Full six-pass research is still separate and is not certified by this scoreability gate.</p>`"),
 (" $('complete').textContent=reviewed+' input-audit checks passed · '+(current.length-reviewed)+' provisional';", " $('complete').textContent=scoreable+' scoreable · '+critical+' missing critical data · '+reviewed+' input-audit checks passed';"),
 ("function auditDetails(a,s){let byid=Object.fromEntries(a.sources.map(v=>[v.id,v]));let ledger=a.input_ledger;let text=", "function auditDetails(a,s){let byid=Object.fromEntries(a.sources.map(v=>[v.id,v]));let ledger=a.input_ledger,q=scoreEligibility(s),withheld=q.status==='missing_critical_data';let text="),
 ("<h3>Eight investment factors: where the MB score comes from</h3><p>Weights total 100%. When information is missing, available components are reweighted and the score remains provisional. TAM, moat and execution are analyst judgments, not measured facts. Checklist completion is not a prediction of returns.</p>", "<h3>Eight investment factors: score inputs and diagnostics</h3><p>Weights total 100%. Missing score-critical information now withholds the total MB/E&V score rather than reweighting available components. Factor diagnostics remain visible to show what is known and missing. TAM, moat and execution are analyst judgments, not measured facts.</p>"),
 ("<tr><th>Total MB screen</th><td>100%</td><td>${num(a.screening_mb_score)}</td><td>${pct(rs(s).mb_input_weight_coverage)}</td><td>${num(a.factors.reduce((n,f)=>n+(f.weighted_contribution||0),0),2)}</td><td class=\"audit-wrap\">${esc(auditLabel(s))}</td></tr>", "<tr><th>Total MB screen</th><td>100%</td><td>${withheld?'<span class=\"audit-badge audit-critical\">Missing Critical Data — no score</span>':num(a.screening_mb_score)}</td><td>${pct(rs(s).mb_input_weight_coverage)}</td><td>${withheld?'—':num(a.factors.reduce((n,f)=>n+(f.weighted_contribution||0),0),2)}</td><td class=\"audit-wrap\">${withheld?esc(q.critical_reasons.join('; ')):esc(auditLabel(s))}</td></tr>"),
 ("<h3>Source-backed score audit</h3><p class=\"notice\"><strong>Full research status: incomplete.</strong>", "<h3>Source-backed score audit</h3>${withheld?'<p class=\"notice critical-text\"><strong>Missing Critical Data — headline MB/E&V scores are withheld and this stock is not ranked.</strong> '+esc(q.critical_reasons.join('; '))+'</p>':''}<p class=\"notice\"><strong>Full research status: incomplete.</strong>")])

patch('multi-bagger-dashboard/build_site.py',[
 ("            for k in ['research_mb_score','research_ev_score','technical_score']:\n                if r.get(k) is None and calculated[k] is None:continue\n                if r.get(k) is None or calculated[k] is None or abs(r[k]-calculated[k])>1e-8:\n                    raise ValueError(f'{s[\"ticker\"]}: monitoring calculation mismatch {k}')\n", "            q=m.get('score_eligibility',{});scoreable=q.get('scoreable') is not False\n            for k in ['research_mb_score','research_ev_score','technical_score']:\n                observed=r.get(k)\n                if not scoreable and k in ['research_mb_score','research_ev_score']:\n                    if observed is not None:raise ValueError(f'{s[\"ticker\"]}: critical-data headline score not withheld')\n                    observed=r.get(k+'_diagnostic')\n                if observed is None and calculated[k] is None:continue\n                if observed is None or calculated[k] is None or abs(observed-calculated[k])>1e-8:\n                    raise ValueError(f'{s[\"ticker\"]}: monitoring calculation mismatch {k}')\n"),
 ("columns=['snapshot','tier','list_rank','ticker'", "columns=['snapshot','tier','list_rank','ticker','score_status','critical_data_reasons'"),
 ("yield dict(zip(columns,[snapshot_id(x),m['tier'],m['tier_rank'],s['ticker'],r.get('price')", "yield dict(zip(columns,[snapshot_id(x),m['tier'],m['tier_rank'],s['ticker'],m.get('score_eligibility',{}).get('status','legacy'),'; '.join(m.get('score_eligibility',{}).get('critical_reasons',[])),r.get('price')"),
 ("'research_values_reconciled':sum(bool(s['metadata'].get('research',{}).get('analyst_grades')) for s in latest['stocks'])})", "'research_values_reconciled':sum(bool(s['metadata'].get('research',{}).get('analyst_grades')) for s in latest['stocks']),\n        'scoreable_count':sum(s['metadata'].get('score_eligibility',{}).get('scoreable') is True for s in latest['stocks']),\n        'critical_data_unscored_count':sum(s['metadata'].get('score_eligibility',{}).get('status')=='missing_critical_data' for s in latest['stocks'])})")])

patch('multi-bagger-dashboard/browser_smoke.py',[
 ("        assert page.locator('#error').is_hidden()\n        page.locator('#group').select_option('all')\n", "        assert page.locator('#error').is_hidden()\n        page.locator('#group').select_option('all')\n        assert 'Missing Critical Data' in page.locator('#ranking').inner_text()\n"),
 ("            if ticker=='POET':assert 'Missing' in page.locator('#evidenceDetail').inner_text()\n", "            if ticker=='POET':assert 'Missing Critical Data' in page.locator('#evidenceDetail').inner_text()\n            if ticker=='IREN':assert 'Missing Critical Data — no score' not in page.locator('#evidenceDetail').inner_text()\n")])
print('Critical-data gate source patches installed.')
