import argparse
import os
from pathlib import Path

import pandas as pd
from alpaca.trading.client import TradingClient
from alpaca.trading.enums import OrderSide, TimeInForce
from alpaca.trading.requests import MarketOrderRequest


DEFAULT_SIGNAL_FILE = Path("reports") / "sp500_signals.csv"


def require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def load_buy_signals(path: Path) -> pd.DataFrame:
    signals = pd.read_csv(path)
    if "signal" not in signals.columns or "symbol" not in signals.columns:
        raise RuntimeError("Signal file must contain symbol and signal columns.")

    buys = signals[signals["signal"].astype(str).str.upper() == "BUY"].copy()
    return buys.sort_values("symbol")


def create_trading_client() -> TradingClient:
    return TradingClient(
        api_key=require_env("ALPACA_API_KEY"),
        secret_key=require_env("ALPACA_SECRET_KEY"),
        paper=True,
    )


def submit_market_buy(client: TradingClient, symbol: str, qty: int):
    order = MarketOrderRequest(
        symbol=symbol,
        qty=qty,
        side=OrderSide.BUY,
        time_in_force=TimeInForce.DAY,
    )
    return client.submit_order(order)


def main() -> None:
    parser = argparse.ArgumentParser(description="Submit Alpaca paper orders from scanner BUY signals.")
    parser.add_argument("--signals", default=str(DEFAULT_SIGNAL_FILE), help="CSV generated by the scanner.")
    parser.add_argument("--qty", type=int, default=1, help="Shares per BUY signal.")
    parser.add_argument("--max-orders", type=int, default=1, help="Maximum number of BUY orders to submit.")
    parser.add_argument("--execute", action="store_true", help="Actually submit orders. Without this, dry-run only.")
    args = parser.parse_args()

    buys = load_buy_signals(Path(args.signals)).head(args.max_orders)

    if buys.empty:
        print("No BUY signals found.")
        return

    print("BUY signals selected for order:")
    print(buys[["symbol", "signal", "close", "reason"]].to_string(index=False))

    if not args.execute:
        print("\nDry run only. Add --execute to submit paper market orders.")
        return

    client = create_trading_client()
    for row in buys.itertuples(index=False):
        submitted = submit_market_buy(client, symbol=row.symbol, qty=args.qty)
        print(
            f"submitted id={submitted.id} "
            f"symbol={submitted.symbol} "
            f"side={submitted.side} "
            f"qty={submitted.qty} "
            f"status={submitted.status}"
        )


if __name__ == "__main__":
    main()
